---
- name: Deploy Docker Image to EKS
  hosts: localhost
  vars:
    image_tag: "{{ image_tag }}"
    docker_hub_repo: "{{ docker_hub_repo }}"
  tasks:
    - name: Update Kubernetes manifest with the new image tag
      replace:
        path: ../Kubernetes/deployment.yml
        regexp: 'IMAGE_TAG'
        replace: "{{ image_tag }}"

    - name: Apply Kubernetes manifests
      command: >
        kubectl apply -f ../Kubernetes/deployment.yml 

    - name: Expose the application using a Kubernetes service
      command: >
        kubectl apply -f ../Kubernetes/service.yml 
