---
- name: Deploy Docker Image to EKS
  hosts: localhost
  vars:
    image_tag: "{{ image_tag }}"
    docker_hub_repo: "{{ docker_hub_repo }}"
  tasks:
    - name: Generate Kubernetes deployment file with the correct image tag
      template:
        src: ../Kubernetes/deployment.yml.j2  # Template file
        dest: ../Kubernetes/deployment.yml    # Output file
        
    - name: Apply Kubernetes manifests
      command: >
        kubectl apply -f ../Kubernetes/deployment.yml --validate=false --kubeconfig /root/.kube/config

    - name: Expose the application using a Kubernetes service
      command: >
        kubectl apply -f ../Kubernetes/service.yml --validate=false --kubeconfig /root/.kube/config
